# Generated by Django 5.1.1 on 2024-09-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('usercomment', models.CharField(db_column='UserComment', max_length=250)),
                ('commentdate', models.DateField(db_column='CommentDate')),
                ('commentid', models.CharField(db_column='CommentID', max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('communityid', models.CharField(db_column='CommunityID', max_length=16, primary_key=True, serialize=False)),
                ('communityname', models.CharField(db_column='CommunityName', max_length=40)),
                ('communitydescription', models.CharField(blank=True, db_column='CommunityDescription', max_length=250, null=True)),
                ('creationdate', models.DateField(db_column='CreationDate')),
            ],
            options={
                'db_table': 'Communities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Communitypost',
            fields=[
                ('cpid', models.CharField(db_column='CPID', max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CommunityPost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Createdposts',
            fields=[
                ('ucpid', models.CharField(db_column='UCPID', max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CreatedPosts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('engageid', models.CharField(db_column='EngageID', max_length=16, primary_key=True, serialize=False)),
                ('engagementtype', models.CharField(db_column='EngagementType', max_length=8)),
                ('engagedate', models.DateField(db_column='EngageDate')),
            ],
            options={
                'db_table': 'Engagement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('joindate', models.DateField(db_column='JoinDate')),
                ('memberid', models.CharField(db_column='MemberID', max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('postid', models.CharField(db_column='PostID', max_length=16, primary_key=True, serialize=False)),
                ('postdescription', models.CharField(blank=True, db_column='PostDescription', max_length=250, null=True)),
                ('imagelink', models.CharField(db_column='ImageLink', max_length=250)),
                ('posttime', models.DateTimeField(db_column='PostTime')),
            ],
            options={
                'db_table': 'Posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('setid', models.CharField(db_column='SetID', max_length=16, primary_key=True, serialize=False)),
                ('private', models.IntegerField(blank=True, db_column='Private', null=True)),
            ],
            options={
                'db_table': 'Settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sharedposts',
            fields=[
                ('sharedate', models.DateField(db_column='ShareDate')),
                ('spid', models.CharField(db_column='SPID', max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SharedPosts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=16, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=40)),
                ('userpassword', models.CharField(db_column='UserPassword', max_length=40)),
                ('joindate', models.DateField(auto_now_add=True, db_column='JoinDate')),
                ('status', models.CharField(db_column='Status', max_length=9)),
                ('bio', models.CharField(blank=True, db_column='Bio', max_length=120, null=True)),
                ('email', models.CharField(db_column='Email', max_length=120)),
                ('firstname', models.CharField(db_column='FirstName', max_length=45)),
                ('lastname', models.CharField(db_column='LastName', max_length=45)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
